-- MySQL Script generated by MySQL Workbench
-- 04/26/14 18:48:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sys_projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_projetos` (
  `sps_id_projeto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sps_projeto` VARCHAR(45) NULL,
  `sps_descricao_resumida` TEXT NULL,
  `sps_descricao_completa` TEXT NULL,
  `sps_data_criacao` DATE NULL,
  `sps_data_revisao` DATE NULL,
  `sps_revisor` VARCHAR(45) NULL,
  PRIMARY KEY (`sps_id_projeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_materias` (
  `smt_id_materia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `smt_materia` VARCHAR(45) NULL,
  `smt_descricao_resumida` TEXT NULL,
  `smt_descricao_completa` TEXT NULL,
  `smt_data_criacao` DATE NULL,
  `smt_data_revisao` DATE NULL,
  `smt_revisor` VARCHAR(45) NULL,
  `smt_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`smt_id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_series` (
  `smt_id_serie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `smt_serie` VARCHAR(45) NULL,
  PRIMARY KEY (`smt_id_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_alunos_analises_cognitivas_evidenciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_alunos_analises_cognitivas_evidenciais` (
  `sac_id_analise` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sac_titulo` VARCHAR(45) NULL,
  `sac_link` VARCHAR(45) NULL,
  `sac_descricao_completa` VARCHAR(45) NULL,
  `sac_data` DATE NULL,
  `sac_responsavel` VARCHAR(45) NULL,
  `fk_sys_instituicoes` INT NULL,
  `fk_sys_alunos` INT NULL,
  PRIMARY KEY (`sac_id_analise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_alunos` (
  `sal_id_aluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sal_nome_completo` VARCHAR(45) NULL,
  `sal_nome_mae` VARCHAR(45) NULL,
  `sal_nome_pai` VARCHAR(45) NULL,
  `sal_login` VARCHAR(45) NULL,
  `sal_senha` VARCHAR(45) NULL,
  `sal_rg` VARCHAR(45) NULL,
  `sal_cpf` VARCHAR(45) NULL,
  `sys_alunos_analises_cognitivas_evidenciais_sac_id_analise` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sal_id_aluno`),
  INDEX `fk_sys_alunos_sys_alunos_analises_cognitivas_evidenciais1_idx` (`sys_alunos_analises_cognitivas_evidenciais_sac_id_analise` ASC),
  CONSTRAINT `fk_sys_alunos_sys_alunos_analises_cognitivas_evidenciais1`
    FOREIGN KEY (`sys_alunos_analises_cognitivas_evidenciais_sac_id_analise`)
    REFERENCES `mydb`.`sys_alunos_analises_cognitivas_evidenciais` (`sac_id_analise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_instituicoes` (
  `sis_id_instituicao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sis_razao_social` VARCHAR(45) NULL,
  `sis_nome_fantasia` VARCHAR(45) NULL,
  `fk_sys_niveis_instituicao` INT NULL,
  `sys_alunos_analises_cognitivas_evidenciais_sac_id_analise` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sis_id_instituicao`),
  INDEX `fk_sys_instituicoes_sys_alunos_analises_cognitivas_evidenci_idx` (`sys_alunos_analises_cognitivas_evidenciais_sac_id_analise` ASC),
  CONSTRAINT `fk_sys_instituicoes_sys_alunos_analises_cognitivas_evidenciais1`
    FOREIGN KEY (`sys_alunos_analises_cognitivas_evidenciais_sac_id_analise`)
    REFERENCES `mydb`.`sys_alunos_analises_cognitivas_evidenciais` (`sac_id_analise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_niveis_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_niveis_instituicao` (
  `sni_id_nivel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sni_nivel` VARCHAR(45) NULL,
  PRIMARY KEY (`sni_id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_analises_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_analises_tipos` (
  `sat_id_analise` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sat_descricao` VARCHAR(45) NULL,
  `sat_descricao_completa` TEXT NULL,
  PRIMARY KEY (`sat_id_analise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_aluno_analises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_aluno_analises` (
  `saa_id_analise` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_analise_tipos` INT NULL,
  `fk_sys_instituicoes` INT NULL,
  `fk_sys_alunos` INT NULL,
  `analise` TEXT NULL,
  `sys_alunos_sal_id_aluno` INT UNSIGNED NOT NULL,
  `sys_instituicoes_sis_id_instituicao` INT UNSIGNED NOT NULL,
  `sys_analises_tipos_sat_id_analise` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`saa_id_analise`),
  INDEX `fk_sys_aluno_analises_sys_alunos1_idx` (`sys_alunos_sal_id_aluno` ASC),
  INDEX `fk_sys_aluno_analises_sys_instituicoes1_idx` (`sys_instituicoes_sis_id_instituicao` ASC),
  INDEX `fk_sys_aluno_analises_sys_analises_tipos1_idx` (`sys_analises_tipos_sat_id_analise` ASC),
  CONSTRAINT `fk_sys_aluno_analises_sys_alunos1`
    FOREIGN KEY (`sys_alunos_sal_id_aluno`)
    REFERENCES `mydb`.`sys_alunos` (`sal_id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_aluno_analises_sys_instituicoes1`
    FOREIGN KEY (`sys_instituicoes_sis_id_instituicao`)
    REFERENCES `mydb`.`sys_instituicoes` (`sis_id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_aluno_analises_sys_analises_tipos1`
    FOREIGN KEY (`sys_analises_tipos_sat_id_analise`)
    REFERENCES `mydb`.`sys_analises_tipos` (`sat_id_analise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_alunos_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_alunos_notas` (
  `san_id_nota` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `san_nota` VARCHAR(45) NULL,
  `fk_sys_instituicoes` INT NULL,
  `fk_sys_alunos` INT NULL,
  `fk_sys_series` INT NULL,
  `san_faltas` VARCHAR(45) NULL,
  `san_justificativas` VARCHAR(45) NULL,
  `fk_sys_materias` VARCHAR(45) NULL,
  `fk_sys_series` INT UNSIGNED NOT NULL,
  `fk_sys_materias` INT UNSIGNED NOT NULL,
  `fk_sys_alunos` INT UNSIGNED NOT NULL,
  `fk_sys_instituicoes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`san_id_nota`),
  INDEX `fk_sys_alunos_notas_sys_series1_idx` (`fk_sys_series` ASC),
  INDEX `fk_sys_alunos_notas_sys_materias1_idx` (`fk_sys_materias` ASC),
  INDEX `fk_sys_alunos_notas_sys_alunos1_idx` (`fk_sys_alunos` ASC),
  INDEX `fk_sys_alunos_notas_sys_instituicoes1_idx` (`fk_sys_instituicoes` ASC),
  CONSTRAINT `fk_sys_alunos_notas_sys_series1`
    FOREIGN KEY (`fk_sys_series`)
    REFERENCES `mydb`.`sys_series` (`smt_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_materias1`
    FOREIGN KEY (`fk_sys_materias`)
    REFERENCES `mydb`.`sys_materias` (`smt_id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_alunos1`
    FOREIGN KEY (`fk_sys_alunos`)
    REFERENCES `mydb`.`sys_alunos` (`sal_id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_instituicoes1`
    FOREIGN KEY (`fk_sys_instituicoes`)
    REFERENCES `mydb`.`sys_instituicoes` (`sis_id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_interesses_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_interesses_eventos` (
  `sie_id_evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sie_titulo` VARCHAR(45) NULL,
  `sie_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`sie_id_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sys_interesses_palavras_chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_interesses_palavras_chave` (
  `sie_id_palavra_chave` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sie_palavra` VARCHAR(45) NULL,
  `fk_interesses_eventos` INT NULL,
  `sys_interesses_eventos_sie_id_evento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sie_id_palavra_chave`),
  INDEX `fk_sys_interesses_palavras_chave_sys_interesses_eventos1_idx` (`sys_interesses_eventos_sie_id_evento` ASC),
  CONSTRAINT `fk_sys_interesses_palavras_chave_sys_interesses_eventos1`
    FOREIGN KEY (`sys_interesses_eventos_sie_id_evento`)
    REFERENCES `mydb`.`sys_interesses_eventos` (`sie_id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
