-- MySQL Script generated by MySQL Workbench
-- 04/27/14 00:32:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema conselheiro_educacional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conselheiro_educacional` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `conselheiro_educacional` ;

-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_projetos` (
  `sps_id_projeto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sps_projeto` VARCHAR(45) NULL,
  `sps_descricao_resumida` TEXT NULL,
  `sps_descricao_completa` TEXT NULL,
  `sps_data_criacao` DATE NULL,
  `sps_data_revisao` DATE NULL,
  `sps_revisor` VARCHAR(45) NULL,
  PRIMARY KEY (`sps_id_projeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_materias` (
  `smt_id_materia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `smt_materia` VARCHAR(45) NULL,
  `smt_descricao_resumida` TEXT NULL,
  `smt_descricao_completa` TEXT NULL,
  `smt_data_criacao` DATE NULL,
  `smt_data_revisao` DATE NULL,
  `smt_revisor` VARCHAR(45) NULL,
  `smt_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`smt_id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_series` (
  `smt_id_serie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `smt_serie` VARCHAR(45) NULL,
  PRIMARY KEY (`smt_id_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_alunos_analises_cognitivas_evidenciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_alunos_analises_cognitivas_evidenciais` (
  `sac_id_analise` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sac_titulo` VARCHAR(45) NULL,
  `sac_link` VARCHAR(45) NULL,
  `sac_descricao_completa` VARCHAR(45) NULL,
  `sac_data` DATE NULL,
  `sac_responsavel` VARCHAR(45) NULL,
  `fk_sys_instituicoes` INT NULL,
  `fk_sys_alunos` INT NULL,
  PRIMARY KEY (`sac_id_analise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_alunos` (
  `sal_id_aluno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sal_nome_completo` VARCHAR(45) NULL,
  `sal_nome_mae` VARCHAR(45) NULL,
  `sal_nome_pai` VARCHAR(45) NULL,
  `sal_login` VARCHAR(45) NULL,
  `sal_senha` VARCHAR(45) NULL,
  `sal_rg` VARCHAR(45) NULL,
  `sal_cpf` VARCHAR(45) NULL,
  `fk_sys_alunos_analises_cognitivas_evidenciais` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sal_id_aluno`),
  INDEX `fk_sys_alunos_sys_alunos_analises_cognitivas_evidenciais1_idx` (`fk_sys_alunos_analises_cognitivas_evidenciais` ASC),
  CONSTRAINT `fk_sys_alunos_sys_alunos_analises_cognitivas_evidenciais1`
    FOREIGN KEY (`fk_sys_alunos_analises_cognitivas_evidenciais`)
    REFERENCES `conselheiro_educacional`.`sys_alunos_analises_cognitivas_evidenciais` (`sac_id_analise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_instituicoes` (
  `sis_id_instituicao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sis_razao_social` VARCHAR(45) NULL,
  `sis_nome_fantasia` VARCHAR(45) NULL,
  `fk_sys_niveis_instituicao` INT NULL,
  `fk_sys_alunos_analises_cognitivas_evidenciais` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sis_id_instituicao`),
  INDEX `fk_sys_instituicoes_sys_alunos_analises_cognitivas_evidenci_idx` (`fk_sys_alunos_analises_cognitivas_evidenciais` ASC),
  CONSTRAINT `fk_sys_instituicoes_sys_alunos_analises_cognitivas_evidenciais1`
    FOREIGN KEY (`fk_sys_alunos_analises_cognitivas_evidenciais`)
    REFERENCES `conselheiro_educacional`.`sys_alunos_analises_cognitivas_evidenciais` (`sac_id_analise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_niveis_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_niveis_instituicao` (
  `sni_id_nivel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sni_nivel` VARCHAR(45) NULL,
  `fk_sys_instituicoes` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sni_id_nivel`),
  INDEX `fk_sys_niveis_instituicao_sys_instituicoes1_idx` (`fk_sys_instituicoes` ASC),
  CONSTRAINT `fk_sys_niveis_instituicao_sys_instituicoes1`
    FOREIGN KEY (`fk_sys_instituicoes`)
    REFERENCES `conselheiro_educacional`.`sys_instituicoes` (`sis_id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_analises_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_analises_tipos` (
  `sat_id_analise` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sat_descricao` VARCHAR(45) NULL,
  `sat_descricao_completa` TEXT NULL,
  PRIMARY KEY (`sat_id_analise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_aluno_analises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_aluno_analises` (
  `saa_id_analise` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_analise_tipos` INT NULL,
  `fk_sys_instituicoes` INT NULL,
  `fk_sys_alunos` INT NULL,
  `analise` TEXT NULL,
  `fk_sys_alunos` INT UNSIGNED NOT NULL,
  `fk_sys_instituicoes` INT UNSIGNED NOT NULL,
  `fk_sys_analises_tipos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`saa_id_analise`),
  INDEX `fk_sys_aluno_analises_sys_alunos1_idx` (`fk_sys_alunos` ASC),
  INDEX `fk_sys_aluno_analises_sys_instituicoes1_idx` (`fk_sys_instituicoes` ASC),
  INDEX `fk_sys_aluno_analises_sys_analises_tipos1_idx` (`fk_sys_analises_tipos` ASC),
  CONSTRAINT `fk_sys_aluno_analises_sys_alunos1`
    FOREIGN KEY (`fk_sys_alunos`)
    REFERENCES `conselheiro_educacional`.`sys_alunos` (`sal_id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_aluno_analises_sys_instituicoes1`
    FOREIGN KEY (`fk_sys_instituicoes`)
    REFERENCES `conselheiro_educacional`.`sys_instituicoes` (`sis_id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_aluno_analises_sys_analises_tipos1`
    FOREIGN KEY (`fk_sys_analises_tipos`)
    REFERENCES `conselheiro_educacional`.`sys_analises_tipos` (`sat_id_analise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_alunos_interesse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_alunos_interesse` (
  `sai_id_aluno_interesse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sai_descricao` VARCHAR(45) NULL,
  `fk_sys_alunos` INT NULL,
  PRIMARY KEY (`sai_id_aluno_interesse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_aluno_nota_justificativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_aluno_nota_justificativa` (
  `snj_id_aluno_nota_justificativa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_sys_justificativas` INT NULL,
  `fk_sys_alunos_notas` INT NULL,
  PRIMARY KEY (`snj_id_aluno_nota_justificativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_alunos_notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_alunos_notas` (
  `san_id_nota` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `san_nota` VARCHAR(45) NULL,
  `fk_sys_instituicoes` INT NULL,
  `fk_sys_alunos` INT NULL,
  `fk_sys_series` INT NULL,
  `san_faltas` VARCHAR(45) NULL,
  `san_justificativas` VARCHAR(45) NULL,
  `fk_sys_materias` VARCHAR(45) NULL,
  `fk_sys_series` INT UNSIGNED NOT NULL,
  `fk_sys_materias` INT UNSIGNED NOT NULL,
  `fk_sys_alunos` INT UNSIGNED NOT NULL,
  `fk_sys_instituicoes` INT UNSIGNED NOT NULL,
  `fk_sys_alunos_interesse` INT UNSIGNED NOT NULL,
  `fh_sys_aluno_nota_justificativa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`san_id_nota`),
  INDEX `fk_sys_alunos_notas_sys_series1_idx` (`fk_sys_series` ASC),
  INDEX `fk_sys_alunos_notas_sys_materias1_idx` (`fk_sys_materias` ASC),
  INDEX `fk_sys_alunos_notas_sys_alunos1_idx` (`fk_sys_alunos` ASC),
  INDEX `fk_sys_alunos_notas_sys_instituicoes1_idx` (`fk_sys_instituicoes` ASC),
  INDEX `fk_sys_alunos_notas_sys_alunos_interesse1_idx` (`fk_sys_alunos_interesse` ASC),
  INDEX `fk_sys_alunos_notas_sys_aluno_nota_justificativa1_idx` (`fh_sys_aluno_nota_justificativa` ASC),
  CONSTRAINT `fk_sys_alunos_notas_sys_series1`
    FOREIGN KEY (`fk_sys_series`)
    REFERENCES `conselheiro_educacional`.`sys_series` (`smt_id_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_materias1`
    FOREIGN KEY (`fk_sys_materias`)
    REFERENCES `conselheiro_educacional`.`sys_materias` (`smt_id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_alunos1`
    FOREIGN KEY (`fk_sys_alunos`)
    REFERENCES `conselheiro_educacional`.`sys_alunos` (`sal_id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_instituicoes1`
    FOREIGN KEY (`fk_sys_instituicoes`)
    REFERENCES `conselheiro_educacional`.`sys_instituicoes` (`sis_id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_alunos_interesse1`
    FOREIGN KEY (`fk_sys_alunos_interesse`)
    REFERENCES `conselheiro_educacional`.`sys_alunos_interesse` (`sai_id_aluno_interesse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_alunos_notas_sys_aluno_nota_justificativa1`
    FOREIGN KEY (`fh_sys_aluno_nota_justificativa`)
    REFERENCES `conselheiro_educacional`.`sys_aluno_nota_justificativa` (`snj_id_aluno_nota_justificativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_interesses_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_interesses_eventos` (
  `sie_id_evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sie_titulo` VARCHAR(45) NULL,
  `sie_descricao` VARCHAR(45) NULL,
  `sie_data` DATE NULL,
  PRIMARY KEY (`sie_id_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_interesses_palavras_chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_interesses_palavras_chave` (
  `sie_id_palavra_chave` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sie_palavra` VARCHAR(45) NULL,
  `fk_interesses_eventos` INT NULL,
  `fk_sys_interesses_eventos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sie_id_palavra_chave`),
  INDEX `fk_sys_interesses_palavras_chave_sys_interesses_eventos1_idx` (`fk_sys_interesses_eventos` ASC),
  CONSTRAINT `fk_sys_interesses_palavras_chave_sys_interesses_eventos1`
    FOREIGN KEY (`fk_sys_interesses_eventos`)
    REFERENCES `conselheiro_educacional`.`sys_interesses_eventos` (`sie_id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_justificativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_justificativas` (
  `sjt_id_justificativa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sjt_descricao` VARCHAR(45) NULL,
  `fk_sys_aluno_nota_justificativa` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sjt_id_justificativa`),
  INDEX `fk_sys_justificativas_sys_aluno_nota_justificativa1_idx` (`fk_sys_aluno_nota_justificativa` ASC),
  CONSTRAINT `fk_sys_justificativas_sys_aluno_nota_justificativa1`
    FOREIGN KEY (`fk_sys_aluno_nota_justificativa`)
    REFERENCES `conselheiro_educacional`.`sys_aluno_nota_justificativa` (`snj_id_aluno_nota_justificativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_tipos_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_tipos_eventos` (
  `ste_id_evento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ste_descricao` VARCHAR(45) NULL,
  `fk_sys_interesses_eventos` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ste_id_evento`),
  INDEX `fk_sys_tipos_eventos_sys_interesses_eventos1_idx` (`fk_sys_interesses_eventos` ASC),
  CONSTRAINT `fk_sys_tipos_eventos_sys_interesses_eventos1`
    FOREIGN KEY (`fk_sys_interesses_eventos`)
    REFERENCES `conselheiro_educacional`.`sys_interesses_eventos` (`sie_id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_categoria_ocorrencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_categoria_ocorrencias` (
  `sco_id_ocorrencia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sco_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`sco_id_ocorrencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_ocorrencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_ocorrencias` (
  `soc_id_ocorrencia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `soc_descricao` VARCHAR(45) NULL,
  `soc_data` DATE NULL,
  `fk_sys_alunos` INT NULL,
  `fk_categoria_ocorrencias` INT NULL,
  `fk_sys_alunos` INT UNSIGNED NOT NULL,
  `fk_sys_categoria_ocorrencias` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`soc_id_ocorrencia`),
  INDEX `fk_sys_ocorrencias_sys_alunos1_idx` (`fk_sys_alunos` ASC),
  INDEX `fk_sys_ocorrencias_sys_categoria_ocorrencias1_idx` (`fk_sys_categoria_ocorrencias` ASC),
  CONSTRAINT `fk_sys_ocorrencias_sys_alunos1`
    FOREIGN KEY (`fk_sys_alunos`)
    REFERENCES `conselheiro_educacional`.`sys_alunos` (`sal_id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_ocorrencias_sys_categoria_ocorrencias1`
    FOREIGN KEY (`fk_sys_categoria_ocorrencias`)
    REFERENCES `conselheiro_educacional`.`sys_categoria_ocorrencias` (`sco_id_ocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conselheiro_educacional`.`sys_reclamacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conselheiro_educacional`.`sys_reclamacoes` (
  `sre_id_reclamacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sre_descricao` VARCHAR(45) NULL,
  `sre_data` DATE NULL,
  `fk_sys_alunos` INT NULL,
  `fk_sys_categoria_ocorrencias` INT NULL,
  `fk_sys_alunos` INT UNSIGNED NOT NULL,
  `fk_sys_categoria_ocorrencias` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`sre_id_reclamacao`),
  INDEX `fk_sys_reclamacoes_sys_alunos1_idx` (`fk_sys_alunos` ASC),
  INDEX `fk_sys_reclamacoes_sys_categoria_ocorrencias1_idx` (`fk_sys_categoria_ocorrencias` ASC),
  CONSTRAINT `fk_sys_reclamacoes_sys_alunos1`
    FOREIGN KEY (`fk_sys_alunos`)
    REFERENCES `conselheiro_educacional`.`sys_alunos` (`sal_id_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_reclamacoes_sys_categoria_ocorrencias1`
    FOREIGN KEY (`fk_sys_categoria_ocorrencias`)
    REFERENCES `conselheiro_educacional`.`sys_categoria_ocorrencias` (`sco_id_ocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
